develop hw1 function and arrow function
tsishchanka/hw_1_tsish pull request #1
Opened 2021-09-05 13:39 UTC by tsishchanka

develop hw1 function and arrow function.

2021-09-05 15:41 UTC, adryianSiarheyeu requested changes

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    } else if (typeof name === "string" && name !== "Mark") {
1. what the purpose of type check here, if you checks it before? 
2.  what if I call your function with lowercased `mark`? add comparison in one register to avoid it

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +};
As I told at the lesson,  if you use `return` inside your if - `else` is redundant

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +        return `${'Hello,'} ${name}${'!'}`;
What the purpose of wrapping `Hello` in `${}`? It is statick string value. Remove curly bracers. The same for `!`

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    const m = 4;
your function must accept triangle's sides as params

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    return (n * n + m * m);
check the Pythagorean theorem.

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    return (x % 2) == 0;
why `==`?

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    if (typeof str == "number")
1.what if I call your function with array? Change another way to check the entire param for a string
2. Why `==`?

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +        value.trim().indexOf(' ') >= 0
what doe's this line for?

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +    const stringValueFirstLetter = stringValueLower.slice(0, 1);
Can be simplifyed to `stringValueLower[0]`

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +}
Try to change the approach of solution. It is so hard;
Tips: check type of entire param --> save first letter of entire word to variable and make it in upper case --> use template string to join first letter and the rest of word

2021-09-05 15:41 UTC, adryianSiarheyeu commented on arrow.js
> +        stringValue += '...'
Params overriding is bad practice. Save intermidiate results into variables

2021-09-05 18:50 UTC, tsishchanka commented on arrow.js
> +        value.trim().indexOf(' ') >= 0
Under the task conditions "Написать функцию которая принимает в себя строчное значение состоящее из одного слова"
typeof value !== 'string' // checking for the "not string" type
typeof value == 'string' && value.trim().indexOf(' ') >= 0 // 1)checking for the string type && if the user entered more than one word (checking for a space) and value.trim() if the user entered one word with a space

2021-09-10 14:09 UTC, adryianSiarheyeu requested changes

2021-09-10 14:09 UTC, adryianSiarheyeu commented on 2hw.js
> +
use ternary operators instead. It will  be more clear

2021-09-19 17:39 UTC, adryianSiarheyeu requested changes

2021-09-19 17:39 UTC, adryianSiarheyeu commented on poke.js
> +    })
task implemented incorrectly. read attentively

2021-09-19 17:39 UTC, adryianSiarheyeu commented on poke.js
> +}
use async await syntax instead then chains

2021-09-27 11:49 UTC, adryianSiarheyeu requested changes

2021-09-27 11:49 UTC, adryianSiarheyeu commented on pokepaint.js
> +
the same comments as in task 2

2021-10-01 12:05 UTC, merged